//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace weblog
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Example
    {
        public int OdaID { get; set; }
        [Required(ErrorMessage="Lütfen Oda Adı Girin")]
        public string OdaAdı { get; set;}
        [Required(ErrorMessage="Lütfen Sayısını Giriniz.")]
        public int OdaSayısı { get; set; }
        [Required(ErrorMessage="Lütfen Kapasiteyi Hesaplayın.")]
        public int OdaKapasıtesı { get; set; }
    }
}
